name: expurgate-solo

services:
  - name: expurgate-solo
    image:
      registry_type: DOCKER_HUB
      repository: smck83/expurgate-solo
      tag: latest

    http_port: 9001

    instance_size_slug: basic-xxs

    envs:
      - key: ZONE
        scope: RUN_TIME
        value: ""
      - key: MY_DOMAINS
        scope: RUN_TIME
        value: ""
      - key: SOURCE_PREFIX
        scope: RUN_TIME
        value: ""
      - key: DELAY
        scope: RUN_TIME
        value: "7200"
      - key: SUPERVISOR_PW
		scope: RUN_TIME
        value: ""
